sonar.projectKey=sonar-solutions_Health-Dashboard
sonar.projectName=Health Dashboard
sonar.organization=sonar-solutions

sonar.sources=backend/app,frontend/src
sonar.tests=backend/tests,frontend/tests
sonar.exclusions=**/node_modules/**,**/__pycache__/**

sonar.python.version=3
sonar.python.coverage.reportPaths=backend/coverage.xml

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.typescript.tsconfigPath=frontend/tsconfig.json
